name: Deploy Next.js application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create .env file
        run: |
          echo "MONGODB_URI=mongodb+srv://root:groot@echomatelite0.wpdzpel.mongodb.net/?retryWrites=true&w=majority" >> .env
          echo "MONGO_PASSWORD=broot" >> .env
          echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env
          echo "AWS_ACCESS_KEY_ID=AKIAWAQBY2R2DXJ3FW6B" >> .env
          echo "AWS_SECRET_ACCESS_KEY=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" >> .env
          echo "AWS_REGION=ap-south-1" >> .env
          echo "AWS_BUCKET_NAME=echomatelite3" >> .env
          echo "NEXT_PUBLIC_BASE_URL=http://localhost:3000" >> .env
          cat .env
      - name: Build Docker image
        run: docker build -t echomatelite/nextjs-app .
      - name: login to docker hub
        run: echo "dckr_pat__qlH09-CRsRH8gbIztaZIBozr8A" | docker login  -u echomatelite --password-stdin
      - name: Push Docker image
        run: docker push echomatelite/nextjs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: pull image from docker hub
        run: docker pull echomatelite/nextjs-app:latest
      - name: delete old container
        run: docker rm -f nextjs-app-contianer
      - name: Run Docker container
        run: docker run -d -p 3000:3000 --name nextjs-app-contianer echomatelite/nextjs-app:latest
